# -*- coding: utf-8 -*-
"""Estatistica com Python_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RAPz7QAPVO5TKAYtUNdJxtkZZ-mCKYgG

# Estatística com Python 02

### Análise de Base de Dados com Pandas e Matplotlib
"""

import pandas as pd

# Base de salários de 13 pessoas
empresa1 = {
    'assistente1': 1000,
    'assistente2': 1080,
    'analista1': 1500,
    'analista2': 1520,
    'analista3': 1600,
    'analista4': 1670,
    'coordenador1': 2640,
    'coordenador2': 2730,
    'coordenador3': 2710,
    'gerente1': 5000,
    'gerente2': 5000,
    'CEO': 57000
}

empresa2 = {
    'assistente1': 3000,
    'assistente2': 3000,
    'analista1': 4200,
    'analista2': 4200,
    'analista3': 4200,
    'analista4': 4200,
    'coordenador1': 6000,
    'coordenador2': 6000,
    'coordenador3': 6000,
    'gerente1': 8000,
    'gerente2': 8000,
    'CEO': 15000
}

print(type(empresa2))

# Inserindo colunas no DataFrame

empresa1 = pd.DataFrame(empresa1.items(), columns=['Cargo', 'Salário'])
empresa2 = pd.DataFrame(empresa2.items(), columns=['Cargo', 'Salário'])

# Exibindo empresa1

display(empresa1)

# Exibindo empresa2

display(empresa2  )

"""## Média"""

media_salario1 = empresa1.Salário.mean()
print('Empresa 1 - Salário: {:.2f}'.format(media_salario1))
media_salario2 = empresa2.Salário.mean()
print('Empresa 2 - Salário: {:.2f}'.format(media_salario2))

"""## Mediana

"""

mediana_salario1 = empresa1.Salário.median()
print('Empresa 1 - Salário: {:.2f}'.format(mediana_salario1))
mediana_salario2 = empresa2.Salário.median()
print('Empresa 2 - Salário: {:.2f}'.format(mediana_salario2))

"""## Moda"""

moda_salario1 = empresa1.Salário.mode()[0]
print('Empresa 1 - Salário: {:.2f}'.format(moda_salario1))
moda_salario2 = empresa2.Salário.mode()[0]
print('Empresa 2 - Salário: {:.2f}'.format(moda_salario2))

# describe()

display(empresa1.describe())

# describe()

display(empresa2.describe())

# Biblioteca Matplotlib

import matplotlib.pyplot as plt

empresa1.plot()
empresa2.plot()

empresa1.hist()
empresa2.hist()

"""# Mais exemplos de manipulação de média, mediana e moda"""

# DataFrame 

valores = {
    'lista1': [1,5,7,9,100] # valores: 5, 7 -> 9 -> 1 -> 100
}

valores = pd.DataFrame(valores)

# Exibindo e Plotando Média

media = valores.lista1.mean()

plt.hist(valores.lista1);
plt.axvline(x=media, color='r', linestyle='-')
plt.show()

print('média: '+ str(media))

# Novo DataFrame

valores = {
    'lista2': [1,5,7,7,9,13,100] # valores: 5, 7 -> 7 -> 9 -> 1 -> 13 -> 100
}

valores = pd.DataFrame(valores)

# Exibindo Média, Mediana, moda e Desvio Padrão e Plotando 

media = valores.lista2.mean()
mediana = valores.lista2.median()
moda = valores.lista2.mode()
desvio_padrao = valores.lista2.std()

plt.hist(valores.lista2);
plt.axvline(x=media, color='r', linestyle='-')
plt.axvline(x=mediana, color='b', linestyle='-')
plt.axvline(x=moda[0], color='g', linestyle='-')
plt.show()

print('média: '+ str(media))
print('mediana: '+ str(mediana))
print('moda: '+ str(moda))
print('desvio padrão: '+ str(desvio_padrao))

x = range(0,len(valores.lista2))

plt.scatter(x,valores.lista2)
plt.axhline(y=media, color='r', linestyle='-')
plt.show()

