# -*- coding: utf-8 -*-
"""Estatistica com Python_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb6OVz_M6f00wZHDVR3uGtwGTAv0Fr-s

# Estatística

Ciência que trabalha com a coleta, análise, estabelecimento e construção de modelos que visam analisar principalmente dados, transformando-os em informação relevante. 

A estatística é um conjunto de técnicas que permite, de forma sistemática, organizar, descrever, analisar e interpretar dados oriundos de estudos ou experimentos, realizados em qualquer área do conhecimento. A estatística descritiva é a etapa inicial da análise de dados e tem por objetivo descrever os dados observados.

# Diferença entre Estatística Descritiva e Inferêncial

* Descritiva: visa a obtenção, organização, redução e representação dos dados estatísticos de forma a auxiliar a descrição do fenômeno observado. A obtenção ou coleta dos dados é normalmente feita através de um questionário ou de observação direta de uma amostra. A organização dos dados consiste na ordenação e crítica quanto à correção dos valores observados. A redução dos dados envolve o entendimento de grande quantidade de dados através da leitura de seus valores individuais. A representação dos dados compreende de técnicas para uma melhor visualização dos dados estatísticos, facilitando a sua compreensão.

* Inferêncial: conseguir generalizar as descobertas feitas no estudo para toda a população de onde os participantes pertencem, se ocupa majoritariamente com desenvolver estimativas sobre os parâmetros populacionais e testar hipóteses.

# Estatística descritiva

### Medidas de posição

Média 
  * Aritimética
  * Geométrica
  * Harmônica

Mediana

Moda

Percentil

Quartil

A moda, a média e a mediana são conhecidas como medidas de tendências centrais.
Elas são utilizadas para representar um conjunto de dados com um único valor.

A moda é o valor com maior frequência absoluta em um conjunto.

A mediana é o valor que está posicionado no centro do conjunto.

Existem vários tipos de média, mas os principais são a média aritmética simples e a média aritmética ponderada.

## Estatísticas com Bibliotecas

* Numpy:  https://numpy.org/doc/stable/
* Statistics: https://docs.python.org/pt-br/dev/library/statistics.html
* Scipy: https://docs.scipy.org/doc/scipy/
"""

# Média

# Biblioteca Numpy
import numpy as np

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", np.mean(pop))

# Biblioteca Statistics
import statistics as stt

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", stt.mean(pop))

# Biblioteca Scipy
import scipy as sp

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", sp.mean(pop))

"""# Mediana"""

# Mediana

# Biblioteca Numpy
import numpy as np

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", np.median(pop))

# Biblioteca Statistics
import statistics as stt

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", stt.median(pop))

# Biblioteca Scipy
import scipy as sp

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81]
print ("The mean is =", sp.median(pop))

"""Biblioteca Statistics

https://docs.python.org/pt-br/3/library/statistics.html
"""

# Moda

# Biblioteca Statistics
import statistics as stt

# População em formato de lista
pop = [13, 23, 31, 49, 56, 81, 81]
print ("The mean is =", stt.mode(pop))